### ISSUE TITLE
Pre-compiled binaries

### ISSUE THREAD

**Issue by mamejay** [endlos99/finalgrom99#2]
Just wondering if you can release pre-compiled binaries.  I have no issues with soldering and programming Atmega chips but I am totally lost with the creation of the files.

Let me know if you can assist.  Thanks

**Comment by endlos99** [comment]
Sure, I actually thought I already pushed the AVR file!

Anyway, the HEX file for the AVR can now be found at avr/finalgrom.hex.  I think it's the latest version 1.3, but if not, you can update the version by using the .avr files in update.

For programming the CPLD, use the file update/update.pld and update your CPLD according to the manual, section "How to Update the FinalGROM 99".

**Comment by mamejay** [comment]
Thank you!!!  That worked perfectly.
