### ISSUE TITLE
Sub folders not loading

### ISSUE THREAD

**Issue by ghhann** [endlos99/finalgrom99#5]
Weird issue. On a beige ti.  I insert the finalgrom and see it as 2 on the menu. I press 2 and get your submenus a b c and so forth.  When I press any submenu. I get a weird screen blip and then no items shown.

I redid the sd card and not working.  I can access the directories on my PC.

Any place to start troubleshooting? 

Best

**Comment by ghhann** [comment]
Never mind appearantly I have a qi motherboard.

**Comment by ghhann** [comment]
Thank you

**Comment by endlos99** [comment]
There is a firmware for QI machines available, but I've just realized that it isn't published in the repo.  Let me find it, then I can include it here as well.

**Comment by ghhann** [comment]
Thanks very much appreciated your hard work and efforts to this project Sent via the Samsung Galaxy A52 5G, an AT&T 5G smartphone
-------- Original message --------From: Ralph Benzinger ***@***.***> Date: 8/8/23  11:08 AM  (GMT-05:00) To: endlos99/finalgrom99 ***@***.***> Cc: ghhann ***@***.***>, Author ***@***.***> Subject: Re: [endlos99/finalgrom99] Sub folders not loading (Issue #5) 
There is a firmware for QI machines available, but I've just realized that it isn't published in the repo.  Let me find it, then I can include it here as well.

**Comment by ghhann** [comment]
Not to bother you but I was wondering if you found the updated firmware for the qi models.I actually just finished another ti99/4a so I have a beige qi model that is now clean and functioning and a black/chrome model which is also clean and functional.Been enjoying seeing what these can do since I never had one in the 80's.All my best and thank you for your help and work and efforts in developing these expansion cartridges....Dr Glenn Hann PhD Sent via the Samsung Galaxy A52 5G, an AT&T 5G smartphone
-------- Original message --------From: ghhann ***@***.***> Date: 8/8/23  11:58 AM  (GMT-05:00) To: endlos99/finalgrom99 ***@***.***>, endlos99/finalgrom99 ***@***.***> Cc: Author ***@***.***> Subject: Re: [endlos99/finalgrom99] Sub folders not loading (Issue #5) Thanks very much appreciated your hard work and efforts to this project Sent via the Samsung Galaxy A52 5G, an AT&T 5G smartphone-------- Original message --------From: Ralph Benzinger ***@***.***> Date: 8/8/23  11:08 AM  (GMT-05:00) To: endlos99/finalgrom99 ***@***.***> Cc: ghhann ***@***.***>, Author ***@***.***> Subject: Re: [endlos99/finalgrom99] Sub folders not loading (Issue #5) 
There is a firmware for QI machines available, but I've just realized that it isn't published in the repo.  Let me find it, then I can include it here as well.

**Comment by endlos99** [comment]
I've added both update files to the updates/ folder in the repo.  I think the update will work on a QI machine, assuming you have the non-QI firmware installed.  The upgrade process is described in the manual:
https://endlos99.github.io/finalgrom99/

For a discussion about the QI firmware (which was created not by me but by Jochen Buur) see here:
https://forums.atariage.com/topic/322211-modify-qi-console-for-finalgrom99-use/

I don't think you'll need to modify your cart, but check that discussion if you still have any problems after the upgrade.

**Comment by ghhann** [comment]
Ralph, 

Hope all is well......was improving on my recovery and I might have bricked my finalgrom99 in loading the qi firmware and uodate.avr.

Getting no response...would it be possible to ship you the board to determine if it is a simple refresh to fix or the board is toast knowing that you don't have a qi if you could restore to v1.3.  Then I'll just use it on a black and metal unit instead of the beige.  If not maybe you can salvage some parts off the board and I can acquire a new one. Let me know either way if it's something you can do or not.  I know I'm asking for a Hugh favor here.  My email is glennhann@comcast.net 

Just added then when installed the led light is solid on no flashing.  Not sure if that helps you maybe if I get a USB blaster to reflash?

Thanks 

Glenn
